exports.RDAs = {
  akassa: "Akassa(Brass)",
  brass: "Brass (Brass)",
  "kaiko/ibeawo": "Kaiko/Ibeawo (Brass)",
  alabini: "Alabini (Ekeremor)",
  alabiri: "Alabiri (Ekeremor)",
  ekeremor: "Ekeremor (Ekeremor)",
  "oporomor-west": "Oporomor West (Ekeremor)",
  "opuokede-creek": "Opuokede Creek (Ekeremor)",
  "kolokuma/opokuma": "Kolokuma/Opokuma (KOLGA)",
  odi: "Odi (KOLGA)",
  "mini-ikensi": "Mini-Ikensi (Nembe)",
  "nembe-east": "Nembe East (Nembe)",
  "nembe-west": "Nembe West (Nembe)",
  "okoroma/tereke": "Okoroma/Tereke (Nembe)",
  anyama: "Anyama (Ogbia)",
  "ogbia-central": "Ogbia Central (Ogbia)",
  ogbia: "Ogbia (Ogbia)",
  "kolo-creek": "Kolo Creek (Ogbia)",
  "mein-oyiakiri": "Mein-Oyiakiri (SALGA)",
  sagbama: "Sagbama (SALGA)",
  tarakiri: "Tarakiri (SALGA)",
  "toru-abubou": "Toru-Abubou (SALGA)",
  "apoi-olodiama": "Apoi Olodiama (SILGA)",
  "bassan-koluama": "Bassan Koluama (SILGA)",
  "bomo-central/west": "Bomo Central/West (SILGA)",
  "bomo-east": "Bomo East (SILGA)",
  "ogboin-north": "Ogboin North (SILGA)",
  "ogboin-south/tarakiri": "Ogboin South/Tarakiri (SILGA)",
  "gbarain-ekpetiama": "Gbarain-Ekpetiama (YELGA)",
  "okordia-zarama-biseni": "Okordia Zarama Biseni (YELGA)",
  yenagoa: "Yenagoa (YELGA)",
};

exports.LGAs = {
  yenagoa: "Yenagoa",
  brass: "Brass",
  ekeremor: "Ekeremor",
  "southern-ijaw": "Southern Ijaw",
  "kolokuma/opokuma": "Kolokuma/Opokuma",
  nembe: "Nembe",
  ogbia: "Ogbia",
  sagbama: "Sagbama"
};
