exports.RDAs = [
  "Akassa (Brass)",
  "Brass (Brass)",
  "Kaiko/Ibeawo (Brass)",
  "Alabini (Ekeremor)",
  "Alabiri (Ekeremor)",
  "Ekeremor (Ekeremor)",
  "Oporomor West (Ekeremor)",
  "Opuokede Creek (Ekeremor)",
  "Kolokuma/Opokuma (KOLGA)",
  "Odi (KOLGA)",
  "Mini-Ikensi (Nembe)",
  "Nembe East (Nembe)",
  "Nembe West (Nembe)",
  "Okoroma/Tereke (Nembe)",
  "Anyama (Ogbia)",
  "Ogbia Central (Ogbia)",
  "Ogbia (Ogbia)",
  "Kolo Creek (Ogbia)",
  "Mein-Oyiakiri (SALGA)",
  "Sagbama (SALGA)",
  "Tarakiri (SALGA)",
  "Toru-Abubou (SALGA)",
  "Apoi Olodiama (SILGA)",
  "Bassan Koluama (SILGA)",
  "Bomo Central/West (SILGA)",
  "Bomo East (SILGA)",
  "Ogboin North (SILGA)",
  "Ogboin South/Tarakiri (SILGA)",
  "Gbarain-Ekpetiama (YELGA)",
  "Okoidia Zarama Biseni (YELGA)",
  "Yenagoa (YELGA",
];

exports.LGAs = [
  "Yenagoa",
  "Brass",
  "Ekeremor",
  "Southern Ijaw",
  "Ekeremor",
  "Kolokuma/Opokuma",
  "Nembe",
  "Ogbia",
];
